version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=wasabi
      - MYSQL_DATABASE=junk
    volumes:
      - ./mysql:/var/lib/mysql
